---
title: "Course Schedule"
tbl-colwidths: [5,15,30,5,5,5,30,5]
editor: visual
---

```{r setup, include = FALSE}
library(lubridate)

wed <- as_date("2024-08-21")
fri <- wed+days(2)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ",day(date))
  return(dm)  
} 
```

This page displays an outline of the topics, content, and assignments
for the semester.

::: column-screen-inset-right
|           Week            | Date                | Topic                                 |                                                                                                                             Reading                                                                                                                             |                                    Video                                    |                         Slides                         | Skill                            |                             Assignment                             |
|:------:|--------|--------|:------------------:|:------:|:------:|--------|:------:|
|                           | `r advdate(fri,0)`  | Course overview                       |                                                                                                                                                                                                                                                                 |                                                                             |                                                        |                                  |                                                                    |
|  [1](/weeks/week-1.html)  | `r advdate(wed,1)`  | The economy and society               | [ðŸ“–](https://www.dropbox.com/scl/fi/eap96p9bori7akhe09shf/GT-Chap-4.pdf?rlkey=rfw3qbru9uatvkkfz0k5o3ikk&dl=0 "Polanyi, Ch. 4") [ðŸ“–](https://www.dropbox.com/scl/fi/jehtn92sojb2veb5no7kg/GT-Chap-11.pdf?rlkey=6w6s42tsbn6xvkn14snves8nc&dl=0 "Polanyi, Ch. 11") |                                                                             |    [ðŸ–¥ï¸](/slides/lecture-1.html "Lecture 1 slides")     | MS 365 GWU                       |                                                                    |
|                           | `r advdate(fri,1)`  | Economic Liberalism                   |                                                                [ðŸ“–](https://www.dropbox.com/scl/fi/clmp5iczsgunz83n2foaz/GT-Chap-12.pdf?rlkey=lguwm9l7avhbi4e0m7r58nijs&dl=0 "Polanyi, Ch. 12")                                                                 |                                                                             |                           ðŸ–¥ï¸                           | Explore Tableau                  |                                                                    |
|  [2](/weeks/week-2.html)  | `r advdate(wed,2)`  | Institutions and development          |                                                                           [ðŸ“–](https://link-springer-com.proxygw.wrlc.org/article/10.1007/s11127-019-00645-z "Acemoglu and Robinson")                                                                           |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-2.1.html "Lecture 2.1 slides")   | Install Excel                    |                                                                    |
|                           | `r advdate(fri,2)`  | Modernization theory                  |                                                      [ðŸ“–](https://www.dropbox.com/scl/fi/h6ezbidqo8451s5kcj2y0/Cheibub-and-Vreeland-2015.pdf?rlkey=98hz9smiosb8mj6y8nd0lq200&dl=0 "Cheibub and Vreeland")                                                       |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-2.2.html "Lecture 2.2 slides")   | Analyzing data                   |                                                                    |
|  [3](/weeks/week-3.html)  | `r advdate(wed,3)`  | Democratic backsliding                |                                                                                              [ðŸ“–](https://doi.org/10.1017/S1537592718003377 "Kaufman and Haggard")                                                                                              | [ðŸ“º](https://www.youtube.com/watch?v=jSl9rydcd7k "Data Assignment 1 Video") |  [ðŸ–¥ï¸](/slides/lecture-3.1.html "Lecture 3.1 slides")   | Importing data                   |                                                                    |
|                           | `r advdate(fri,3)`  | The resource curse                    |                                                                                            [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10 "Ross")                                                                                             |              [ðŸ“º](https://www.youtube.com/watch?v=y7ESq_O3Odw)              |  [ðŸ–¥ï¸](/slides/lecture-3.2.html "Lecture 3.2 slides")   | Organizing data                  |   [ðŸ§®](/assignments/data-assignment-1.html "Data assignment 1")    |
|  [4](/weeks/week-4.html)  | `r advdate(wed,4)`  | Women's empowerment                   |                                                                            [ðŸ“–](https://www.econstor.eu/bitstream/10419/216551/1/cesifo1_wp8155.pdf "Hassami and Lopes da Fonseca")                                                                             |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-4.1.html "Lecture 4.1 slides")   | Bar charts                       |                                                                    |
|                           | `r advdate(fri,4)`  | Exam 1 review                         |                                                                                                                                                                                                                                                                 |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-4.2.html "Lecture 4.2 slides")   | Line charts                      |                                 ðŸ“˜                                 |
|  [5](/weeks/week-5.html)  | `r advdate(wed,5)`  | Programmatic politics vs. clientelism |                                                   [ðŸ“–](https://blackboard.gwu.edu/webapps/blackboard/execute/content/file?cmd=view&mode=designer&content_id=_12817119_1&course_id=_380501_1 "Stokes et. al.")                                                   |                                                                             | [ðŸ–¥ï¸](/slides/lecture-5.1.html "Distributive politics") | Scatter plots                    |                                                                    |
|                           | `r advdate(fri,5)`  | Vote buying                           |                                                                                       [ðŸ“–](https://ebookcentral.proquest.com/lib/gwu/reader.action?docID=5732981&ppg=112)                                                                                       |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-5.2.html "Lecture 5.2 slides")   | Maps                             |                                                                    |
|  [6](/weeks/week-6.html)  | `r advdate(wed,6)`  | Ethnicity and public goods            |                                                                                                       [ðŸ“–](http://www.jstor.org/stable/25054263 "Miguel")                                                                                                       |  [ðŸ“º](https://www.youtube.com/watch?v=G9vKgrtDZ-w&t=72s "Bar chart video")  |  [ðŸ–¥ï¸](/slides/lecture-6.1.html "Lecture 6.1 slides")   | Creating bar charts in Excel     |                                                                    |
|                           | `r advdate(fri,6)`  | Democracy and redistribution          |                                                                                  [ðŸ“–](https://doi-org.proxygw.wrlc.org/10.1017/S1537592717002122 "Holland and Ross Schneider")                                                                                  | [ðŸ“º](https://www.youtube.com/watch?v=YOpwcihO-iY&t=39s "Line chart video")  |  [ðŸ–¥ï¸](/slides/lecture-6.2.html "Lecture 6.2 slides")   | Creating line charts in Excel    |                                                                    |
|  [7](/weeks/week-7.html)  | `r advdate(wed,7)`  | Washington consensus reforms          |                                                                         [ðŸ“–](https://www.brookings.edu/wp-content/uploads/2021/02/Washington-Consensus-Reforms.pdf "Archibong et. al.")                                                                         |   [ðŸ“º](https://www.youtube.com/watch?v=NDszBjbvSFA "Scatter plot video")    |  [ðŸ–¥ï¸](/slides/lecture-7.1.html "Lecture 7.1 slides")   | Creating scatter plots in Excel  |                                                                    |
|                           | `r advdate(fri,7)`  | No class, fall break                  |                                                                                                                                                                                                                                                                 |                                                                             |                                                        | ðŸðŸ‚ðŸŽƒ                           |                                                                    |
|  [8](/weeks/week-8.html)  | `r advdate(wed,8)`  | The gendered legacy of reform         |                                                                      [ðŸ“–](https://eresgw-wrlc-org.proxygw.wrlc.org/x/docs/gelm/teitelbaum_emmanuel/LourdesChapter3.pdf "Beneria et. al.")                                                                       |      [ðŸ“º](https://www.youtube.com/watch?v=ixjWeXbYVl0 "Mapping video")      |  [ðŸ–¥ï¸](/slides/lecture-7.2.html "Lecture 7.2 slides")   | Creating Maps in Excel           |                                                                    |
|                           | `r advdate(fri,8)`  | Labor and development                 |                                                                                                                               ðŸ“–                                                                                                                                |                                                                             |                           ðŸ–¥ï¸                           |                                  |   [ðŸ§®](/assignments/data-assignment-2.html "Data assignment 2")    |
|  [9](/weeks/week-9.html)  | `r advdate(wed,9)`  | Populism and social policy            |                                                                                   [ðŸ“–](https://onlinelibrary-wiley-com.proxygw.wrlc.org/doi/full/10.1111/dech.12578 "Putzel")                                                                                   |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-8.1.html "Lecture 8.1 slides")   | Writing with Zotero              |                                                                    |
|                           | `r advdate(fri,9)`  | Exam 2 review                         |                                                                                                                                                                                                                                                                 |                                                                             |  [ðŸ–¥ï¸](/slides/lecture-8.2.html "Lecture 8.2 slides")   | Install Tableau                  |                                 ðŸ“˜                                 |
| [10](/weeks/week-10.html) | `r advdate(wed,10)` | Welfare states in the OECD            |                                                  [ðŸ“–](https://blackboard.gwu.edu/webapps/blackboard/execute/content/file?cmd=view&mode=designer&content_id=_12817120_1&course_id=_380501_1 "Epsing-Andersen")                                                   |                                                                             | [ðŸ–¥ï¸](/slides/lecture-10.1.html "Lecture 10.1 slides")  | Wrangling data in Power Query    |                                                                    |
|                           | `r advdate(fri,10)` | U.S. exceptionalism                   |                                                                               [ðŸ“–](https://www.brookings.edu/wp-content/uploads/2001/06/2001b_bpea_alesina.pdf "Alesina et. al.")                                                                               |                                                                             | [ðŸ–¥ï¸](/slides/lecture-10.2.html "Lecture 10.2 slides")  |                                  |   [âœï¸](/project/project-assignment-1.qmd "Project Assignment 1")   |
| [11](/weeks/week-11.html) | `r advdate(wed,11)` | Unions and collective bargaining      |                                                                      [ðŸ“–](https://journals-sagepub-com.proxygw.wrlc.org/doi/full/10.1177/0143831X18780327 "Gumbrell-McCormick and Hyman")                                                                       |                                                                             | [ðŸ–¥ï¸](/slides/lecture-11.1.html "Lecture 11.1 slides")  | Create visualizations in Tableau |                                                                    |
|                           | `r advdate(fri,11)` | Varieties of capitalism               |                                                                                          [ðŸ“–](https://academic.oup.com/book/301/chapter/134893294 "Hall and Soskice")                                                                                           |                                                                             | [ðŸ–¥ï¸](/slides/lecture-11.2.html "Lecture 11.2 slides")  |                                  |                                                                    |
| [12](/weeks/week-12.html) | `r advdate(wed,12)` | Globalization                         |                                                                              [ðŸ“–](https://www.annualreviews.org/doi/full/10.1146/annurev-economics-080315-015041 "Autor et. al.")                                                                               |                                                                             | [ðŸ–¥ï¸](/slides/lecture-12.1.html "Lecture 12.1 slides")  | Create a Tableau dashboard       |                                                                    |
|                           | `r advdate(fri,12)` | Inequality                            |                                                                                  [ðŸ“–](https://www.amazon.com/gp/product/B07P92PDLF/ref=dbs_a_def_rwt_bibl_vppi_i2 "Stiglitz")                                                                                   | [ðŸ“º](https://www.youtube.com/watch?v=yqAYuAf6zEc&t=175s "Wrangling Video")  | [ðŸ–¥ï¸](/slides/lecture-12.2.html "Lecture 12.2 slides")  |                                  |  [âœï¸](/project/project-assignment-2.html "Project Assignment 2")   |
| [13](/weeks/week-13.html) | `r advdate(wed,13)` | The populist backlash                 |                                                                                            [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctv2dzzqsn "Judis")                                                                                             |                                                                             | [ðŸ–¥ï¸](/slides/lecture-13.1.html "Lecture 13.1 slides")  |                                  |                                                                    |
|                           | `r advdate(fri,13)` | Extremist politics                    |                                                                                            [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctv2dzzqsn "Judis")                                                                                             |                                                                             | [ðŸ–¥ï¸](/slides/lecture-13.2.html "Lecture 13.2 slides")  |                                  |                                                                    |
| [14](/weeks/week-14.html) | `r advdate(wed,14)` | No class, Thanksgiving break          |                                                                                                                                                                                                                                                                 |                                                                             |                                                        | ðŸ¦ƒðŸ¥§ðŸ´                           |                                                                    |
|                           | `r advdate(fri,14)` | No class, Thankgiving break           |                                                                                                                                                                                                                                                                 |                                                                             |                                                        |                                  |                                                                    |
| [15](/weeks/week-15.html) | `r advdate(wed,15)` | Final project presentations           |                                                                                                                                                                                                                                                                 |           [ðŸ“º](https://youtu.be/BQwm3Z39Ne8 "Tableau dashboard")            |                                                        |                                  |                                                                    |
|                           | `r advdate(fri,15)` | Exam 3 review                         |                                                                                                                                                                                                                                                                 |                                                                             |                                                        |                                  | ðŸ“˜ [âœï¸](/project/project-assignment-3.html "Project Assignment 3") |
:::
