---
title: "Lecture 7.2"
subtitle: "The Gendered Legacy of Reform"
author: "Emmanuel Teitelbaum"
footer: "[PSC 2339 Website](https://psc2339.com)"
logo: "images/cpe_logo.png"
format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
execute:
  echo: false
  freeze: auto
---

# Economic Crises

## Sri Lanka

- Swimming in the [president's pool](https://www.bbc.com/news/av/world-asia-62105698)
- Causes of the crisis
  - Years of economic mismanagement under Rajapaksas
  - Rajapaksa govt. cut taxes after it came to power in 2019
  - Banned fertilizer which decimated rice crop (staple)
  - COVID-19 killed demand for tourism and remittances
  - Then war in Ukraine led to grain shortages
  - Sri Lanka ran out of money couldn't by fuel or medicine
  
## Discussion

- Where is Sri Lanka [now](https://www.nytimes.com/2023/01/31/business/sri-lanka-economy.html)?
  - What is the IMF doing?
- What is the World Bank [doing](https://blogs.worldbank.org/endpovertyinsouthasia/sri-lankas-crisis-offers-opportunity-reset-its-development-model)?  
- In what ways is the Bank's approach similar to or different from the one proposed by the Washington Consensus? 
 
## Lebanon

- When robbing a bank seems [perfectly justified](https://www.nytimes.com/2023/02/28/opinion/lebanon-crisis-economy-bank-robbers.html)

- Read about the [World Bank's](https://www.worldbank.org/en/country/lebanon/overview#1) assistance to Lebanon

- How is the Bank's strategy similar to or different from its strategy in Sri Lanka?

- Which strategy is better, the one being pursued in Sri Lanka or the one being pursued in Lebanon?

# Women and the Washington Consensus

## Discussion 1

- What does Benaría mean by the term “feminization of labor” How is it manifested in the following sectors/activities? 
	- Manufacturing
	- Agriculture
	- Services
	- Migration
	- Human Trafficking

## Discussion 2

- Benería identifies three potential effects of women’s employment on gender relations. 
	- Liberating
	- Intensifying
	- Reconstitution of gender inequalities
- Describe each of these. Which effect do you think is the strongest? 


# Policy Models

## Policy Models

- What policies effectively increase women’s empowerment?
- Three (that we’ll consider)
	- Empowerment through development 
	- Electoral quotas 
	- Empowerment through finance/microcredit 
- Two things to consider
	- Effectiveness
	- Attainability

## Development and Empowerment (Duflo)

- Discussion
- Development --> Empowerment
  - How does development empower women? 
  - Is development the solution to discrimination and VAW? 

- Empowerment --> Development
  - What does Duflo mean by "empowerment"?  
  - Is empowering women the answer for development?  

## Gender Quotas (Beaman) {.smaller}

- Districts randomly selected for reserved seats
- Some districts selected more than once
- Basic findings
	- Districts selected twice in a row see changes in how parents view daughters and how girls perceive themselves
	- Districts selected twice in a row see improvements in educational outcomes for girls
	- No effects on labor force participation and education outcomes for older women 
- Mechanisms:
	- Changing policies (which changes beliefs)
	- Providing role models

## Grameen Bank

- Muhammad Yunus
	- Winner of Nobel Peace Prize (and GW President's Medal)

- Inspired by stool makers of Jobra village
	- Earned 2 cents per day

- Set up Grameen bank to fill credit void for rural women

- Repayment based on trust


## Think About
- Which Model is Most Compelling? 
	- Development 
	- Gender Quotas
	- Microcredit

- Why? 